version: '3.9'

services:

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  web:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@host.docker.internal:5432/${DB_NAME}
      REDIS_URL: redis://redis:6379/0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - media_files:/app/media
      - log_files:/app/logs
    depends_on:
      - redis
    ports:
      - "8000:8000"
    command: >
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --timeout 120
      --access-logfile -
      --error-logfile -

volumes:
  redis_data:
  media_files:
  log_files:
