# Generated by Django 5.2.12 on 2026-04-03 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_area_created_by'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='areas.area'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_area', 'Admin de Área'), ('trabajador', 'Trabajador de Área')], default='trabajador', max_length=20),
        ),
    ]
