# Generated by Django 5.2.12 on 2026-04-03 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('areas', '0002_area_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='areas.area'),
        ),
    ]
