# Generated by Django 5.2.15 on 2026-06-24 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0002_area_created_by"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="companies.company",
            ),
        ),
    ]
